# Generated by Django 2.2.11 on 2020-11-20 17:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150, verbose_name='question')),
                ('is_general', models.BooleanField(verbose_name='is_general')),
                ('categories', models.CharField(max_length=100, verbose_name='categories')),
                ('point', models.PositiveIntegerField(verbose_name='point')),
                ('icon_url', models.URLField(null=True, verbose_name='icon_url')),
                ('duration', models.PositiveIntegerField(verbose_name='duration')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date_created')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=70, verbose_name='choice')),
                ('is_correct_choice', models.BooleanField(verbose_name='is_correct_choice')),
                ('is_icon_url', models.URLField(null=True, verbose_name='is_icon_url')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question.Question')),
            ],
        ),
    ]
