# Generated by Django 2.2.11 on 2020-11-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20201120_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150, verbose_name='question'),
        ),
        migrations.AlterUniqueTogether(
            name='choices',
            unique_together=set(),
        ),
    ]
