# Generated by Django 2.2.11 on 2020-11-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20201120_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150, unique=True, verbose_name='question'),
        ),
    ]
